---
output: github_document
---

## Reading prompts


## week 2

Tufte, Edward (1997) The decision to launch the space shuttle Challenger. 
In: *Visual and statistical thinking: Displays of evidence for making
decisions.* Cheshire, CT: Graphics Press, 16--31.


**Prompt:** Tufte says, "Regardless of the indirect cultural causes of the
accident, there was a clear proximate cause." Summarize Tufte's explanation 
of the proximate cause.  

**Response:** 


**Prompt:** Describe the evidence the author presents to support those ideas.


**Response:**  






**Prompt:** What data were used in making the decision to launch? What data 
were not used but should have been used (according to Tufte) in making the
launch decision?


**Response:** 



**Prompt:** On page 23, Tufte presents a graph that provides visual evidence
that the "launch was completely outside the engineering database accumulated 
in 24 previous flight." Describe the structure of this data set:

- Number of observations 
- Data structure: classify each variable as quantitative (continuous or discrete) and categorical (nominal or ordinal and number of levels). 


**Response:**  





**Prompt:** Summarize the main thesis of the paper.  


**Response:** 






## week 4

Wainer, Howard (2014) Fifteen displays about one thing. In: *Medical
illuminations: Using evidence, visualization, and statistical thinking to
improve healthcare.* UK: Oxford University Press, 32--49.

**Prompt:** 


**Response:** 


**Prompt:** 


**Response:**  


**Prompt:**  


**Response:** 





## week 6

Dragga, Sam & Dan Voss (2001) Cruel pies: The inhumanity of technical
illustrations. *Technical Communication* 48(3): 265--274.

**Prompt:** 


**Response:** 


**Prompt:** 


**Response:**  


**Prompt:**  


**Response:** 




## week 8

Kostelnick, Charles (2007) The visual rhetoric of data displays: The conundrum
of clarity. *IEEE Transactions on Professional Communication* 50(2): 280--294.

**Prompt:** 


**Response:** 


**Prompt:** 


**Response:**  


**Prompt:**  


**Response:** 





## week 10

Spence, Ian (2006) William Playfair and the psychology of graphs. In: *IEEE
Transactions on Professional Communication.* Alexandria, VA: American
Statistical Association, section on statistical graphics, 2426--2436.

**Prompt:** 


**Response:** 


**Prompt:** 


**Response:**  


**Prompt:**  


**Response:** 




