---
output: github_document
---

## organizing your files

If you were successful in following the project setup instructions, you have a folder called *me447_visualizing-data* on your machine and you have successfully made it an RStudio project. Your course directory should look like this:

    me447_visualizing-data
      `- me447_visualizing-data.Rproj

In your course folder, please create sub-folders (or sub-directories) called *data*, *design*, *learnR*, *portfolio*, and *visuals*. In the tutorials, I use relative file paths that depend on this file organization. 

- *data* is for all data files and the R files to reshape the data,
preparing it for graphing.
- *design* is for the R files that operate on the prepared data
files to produce the data graphic images saved in *visuals.*
- *portfolio* is for your portfolio drafts, feedback, and critiques.
- *learnR* is for files you write or download to learn R. For
example, this would be the directory in which you save the R files you write as you work through this ”Getting started” lesson. 

The course directory should look like this: 

    me447_visualizing-data
      |- data
      |- design 
      |- learnR 
      |- portfolio 
      |- visuals
      `- me447_visualizing-data.Rproj

You may add folders to this organization as you become familiar with the software. 

Different ways of organizing files can be used, of course --- the important thing is that you plan the organization from the beginning and then stick to it (for that project). The point of organizing your files now is to "make your workflow more coherent from the beginning and save you a lot of backtracking later on." (Gandrud, 2014)

Next tutorial: [Interacting with R in the Console](cm011_using-console.md)

[^1]:Christopher Gandrud (2014) *Reproducible Research with R and RStudio*, Chapman & Hall/CRC, pp.18.

---

[main page](../README.md)<br> 
[topics page](cm001_org-by-topic.md)
