---
output: github_document
bibliography: "../resources/bib/refs.bib" 
csl: "../resources/styles/journal-of-peace-research.csl"
link-citations: yes
---

```{r echo=FALSE}
library(knitr)
opts_knit$set(root.dir = "../")
opts_chunk$set(echo = FALSE, message = FALSE, collapse = TRUE, warning = FALSE)
```

## D1 distributions 

Univariate data are measurements of a single quantitative variable. The data can be separated into groups by a categorical variable, creating one distribution for each level of the category for comparison. 

We will use three prospective graph designs for comparing distributions 

- histograms 
- density plots 
- box plots 

Include only one of these graph types in your portfolio. Select the design that best conveys the stories in your data. 




## data 

Data for these graphs are univariate with at least 200 values total. 

These data must also include at least one categorical variable to sort the data into at least three groups for comparison. 

- If one category is used, it must have at least three levels for a minimum of three comparisons.  
- If two categories are used, they must have at least two levels each for a minmum of four comparisons. 




