---
output: github_document
bibliography: "../resources/bib/refs.bib" 
csl: "../resources/styles/journal-of-peace-research.csl"
link-citations: yes
---

```{r echo=FALSE}
library(knitr)
opts_knit$set(root.dir = "../")
opts_chunk$set(echo = FALSE, message = FALSE, collapse = TRUE, warning = FALSE)
```

## D7 self-taught 

This is a graph type you learn to construct on your own. Select one only from the list and include it in the portfolio. 

Counts 

- quantile-quantile (q-q) plot
- cycle plot (month plot) 
- Sankey diagram 
- mosaic 
- diverging stacked bar 

Spatial data 

- quantitative map
- qualitative map







## data

### q-q plot

The quantile-quantile (q-q) plot is a graphical technique for determining if two groups of data come from populations with a common distribution. Data requirements: 

- Two samples of one quantitative variable, min. 200 observations total. 
- One categorical variable that defines the two groups (two levels only) 
- The sample sizes of the two groups do not need to be equal 
  
For additional technical details, see @nist-q-q. 




### cycle plot 



For additional technical details, see 



### Sankey diagram	




For additional technical details, see 


### mosaic	




### diverging stacked bar 

Diverging stacked bar charts are the primary graphical display technique for reporting survey data. Respondents are typically asked to choose one response from a discrete number of options such as Strongly Disagree, Disagree, No Opinion, Agree, Strongly Agree. 



For additional technical details, see @HeibergerRobbins2014. 





### quantitative map	


For additional technical details, see 




### qualitative map 

For additional technical details, see 




## references

<div id="refs"></div>



---    
[Portfolio data summary](cm301_portfolio_data-types.md)    
[Calendar](../README.md#calendar)    
[Index](../README.md#index) 
