---
output: github_document
bibliography: "../resources/bib/refs.bib" 
csl: "../resources/styles/journal-of-peace-research.csl"
link-citations: yes
---

```{r echo=FALSE}
library(knitr)
opts_knit$set(root.dir = "../")
opts_chunk$set(echo = FALSE, message = FALSE, collapse = TRUE, warning = FALSE)
```

# portfolio lab

- [Media] 
- [README] 
- [Reports] 
- [Data tables] 
- [Importing images] 
- [Citations and references] 
- [Discussion notes]


## media 

Your portfolio is a website in the form of a GitHub repository. The repo is private, accessible only to people you invite as collaborators. However, I expect you to treat these pages as if you intended to make them available to a prospective employer. 

[This sample](https://github.com/graphdr/portfolio-sample) shows the basic layout of the portfolio website we are about to start building.  


## readme 

The README file is the main page of the website. README introduces the reader to your portfolio and provides navigation links to  

- Displays and critiques  
- Your reading responses and roundtable e-notes 

Editing the README file. 




## reports

One Rmd report is written per display. Each report describes the data, the graph design, and elements of visual rhetoric relevant to the story. 

Creating the first report shell. 




## data tables 

@Few2012




## importing images




## citations and references 






## discussion notes 

Visual design and rhetorical decisions are expected to be supported by evidence from our readings and roundtable discussions. These notes are your record of key points of evidence to be used in your reports. 

Creating the reading response shell. 

Creating the roundtable e-notes shell. 








<!-- portfolio checklist (revise)  -->

<!-- describe, discuss, and critique  -->

<!-- sample portfolio entries  -->

<!-- commit-pull-push  -->





## references

<div id="refs"></div>

---  
[Calendar](../README.md#calendar)    
[Index](../README.md#index) 

