---
output: github_document
---

## readings for discussion

Tufte (1997) Challenger launch decision. Check out a copy from me. 

Charles Kostelnick (Dec 2007) The visual rhetoric of data displays: The conundrum of clarity, *IEEE Transactions on Professional Communication* 50(4), 280–294.

Howard Wainer (2014) Fifteen displays about one thing, Sections 2.9 and 2.10 from *Medical Illuminations: Using Evidence, Visualization, and Statistical Thinking to Improve Healthcar*e, Oxford, UK: Oxford University Press, 32–49. 

Sam Dragga and Dan Voss (Aug 2001) Cruel pies: The inhumanity of technical illustrations, *Technical Communication*, 48(3), 265–274.

Ian Spence (2006) William Playfair and the psychology of graphs, *Proceedings of the American Statistical Association, Section on Statistical Graphics*, Alexandria VA: American Statistical Association, 2426–2436.



## readings for enlightenment

Charles Kostelnick (Nov 1998) Conflicting standards for designing data displays: Following, flouting, and reconciling them, *Technical Communication* 45(4), 473–482.

Stephen Few (2012) Differing roles of tables and graphs, Chapter 3 from *Show Me the Numbers: Designing Tables and Graphs to Enlighten*, 2/e, Burlingame, CA: Analytics Press, 39–51.

Howard Wainer (1997) Graphical failures: How to display data badly, Chapter 1 from *Visual Revelations: Graphical Tales of Fate and Deception From Napoleon Bonaparte To Ross Perot*, London: Lawrence Erlbaum Associates, 5–46. 

Jean-luc Doumont (2009) Designing the graph, from *Trees, maps, and theorems: Effective communication for rational minds*, Belgium: Principiae, 133–143.

Constable (2017) Color (online)

Storytelling with data (online)


## readings from the text

Ch 2: Limitations of some common charts and graphs<br> 
Ch 4: Some more effective graphs in one or two dimensions<br> 
Ch 5: Trellis graphics and other ways to display more than two variables<br> 
Ch 6: General design principles for creating effective graphs<br> 
Ch 7: Scales<br> 
Ch 8: Applying what we've learned: *Before* and *after* example<br> 
Ch 10: Questions and answers<br> 



 


---

[main page](../README.md)<br> 
[topics page](README-by-topic.md)
