---
output: github_document
---

# me447 visualizing data

- Browse this page for material organized topically 
- [Browse the main page](../README.md) for material organized chronologically 

## course management

- [Calendar](../cm/admin-02_calendar.pdf) 
- [Syllabus](../cm/admin-03_syllabus.md)

## resources 

- [Help links](../cm/admin-04_getting-help.md) and references I use regularly  
- [Further reading](http://www.graphdoctor.com/archives/154) on graph design
- [References](../cm/admin-05_references.md) cited in the notes and tutorials 


## readings

- [Required reading list](../cm/read-02_reading-list.md)
- A written response form is included in your course handbook (or you can view it [here](../cm/read-01_reading-response-form.pdf)). Use it to thoughtfully answer the prompts and bring to class on the due date.

## portfolio

- [Requirements](../cm/folio-01_portfolio-requirements.md)
- Portfolio checklist is included in your course handbook (or you can view it [here](../cm/folio-02_portfolio-checklist.pdf)). Use it to check off requirements as you complete them.

## tutorials

File management

- [Organizing your files](../cm/tut-01_organize-files.md)
- [Using Windows Notepad for CSV files](../cm/tut-04_notepad-for-csv.md) 
- Basic file management 

Interacting with R using RStudio

- [Interacting with R in the Console](../cm/tut-02_using-console.md)
- [Interacting with R using scripts](../cm/tut-03_using-scripts.md)

Display types  

- Scatterplots
- Dot plots 
- Multiways 
- Tables
- Box plots 
- Small multiples 

Data

- Data basics 
- Subsetting data 
- Reshaping data 
- Finding interesting data 

Documents 

- Markdown basics 
- Document design 1
- Document design 2
- Front and back matter 

Design and rhetoric 

- Color 
- Match display to data type 
- Learning new graph types on your own  
- Designing your own data graphics






---

[main page](../README.md)
