---
output: github_document
bibliography: "../manage/refs.bib" 
csl: "../manage/csl/journal-of-peace-research.csl"
---

```{r echo=FALSE}
library(knitr)
opts_knit$set(root.dir = "../")
opts_chunk$set(echo = TRUE, message = FALSE, collapse = TRUE, warning = FALSE, cache = TRUE, cache.path = "tut-07-cache/08-", fig.path = "tut-07-images/08-")
```


```{r include=FALSE}
library(dplyr)
library(tibble)
library(ggplot2)

# dataset in R, 1973–74 models, Motor Trend
data(mtcars)

# when row names contain data (not tidy)
library(dplyr)
my_mtcars <- mtcars %>%
	mutate(make_model = row.names(mtcars))
library(tibble)

# OK, but treated as continuous var, actually discrete
my_mtcars <- my_mtcars %>%
	mutate(Cylinders = factor(cyl))

# instead of colors, could use panels
f8 <- ggplot(data = my_mtcars, aes(x = mpg, y = reorder(make_model, mpg))) +
	geom_point(size = 3) +
	facet_grid(~ Cylinders)
```







## change the order of the facets

We can change the panel order with *reorder()*  inside *facet_grid()*. Here we reorder the panels (*Cylinder* variable) based on the magnitude of the *mpg* variables in each panel. 

```{r}
# reorder panels
f9 <- f8 +
	facet_grid(~ reorder(Cylinders, mpg))
print(f9)
```

Next tutorial: [set the y scales free](tut-0709_free-scales.md)<br>
Tutorial list: [week 2](week-02_assignments.md)  

---
 
[main page](../README.md)<br>
[topics page](../README-by-topic.md) 




