---
title: finding interesting data
output: 
  github_document:
    toc: TRUE
    toc_depth: 2
bibliography: "../manage/refs.bib" 
csl: "../manage/csl/journal-of-peace-research.csl"
---

```{r 1201, echo=FALSE}
library(knitr)
opts_knit$set(root.dir = "../")
opts_chunk$set(echo = TRUE, message = FALSE, collapse = TRUE, warning = FALSE, cache = TRUE, cache.path = "tut-12-cache/02-", fig.path = "tut-12-images/02-")
```


I spent some time browsing my usual suspects list of R sites and found the following links that show some promise for finding interesting data for your work. 

If you find other sites you find useful or entertaining, please let me know and I'll add them to the lists. 

## assignment 

Regularly browse these links (or find your own) to 

- find interesting data for the graphs in your portfolio 
- find interesting visualizations to use as a basis for D7 and D8 




## articles about finding interesting data 

- [Fun data for teaching R](https://bartomeuslab.com/2016/01/21/fun-data-for-teaching-r/) blog  
- [Discovering good data packages](https://ropenscilabs.github.io/data-packages/) repo  
- [R packages for data access](http://blog.revolutionanalytics.com/2016/08/r-packages-data-access.html) blog  
- [19 free public data sets for your first data science project](https://www.springboard.com/blog/free-public-data-sets-data-science-project/)  

## others' tutorials 

- [Getting data from the web part 1](https://github.com/STAT545-UBC/STAT545-UBC.github.io/blob/master/webdata02_activity.md) tutorial from Stat 545 by Jenny Bryan  
- [Getting data from the web part 2](https://github.com/STAT545-UBC/STAT545-UBC.github.io/blob/master/webdata03_activity.md) tutorial from Stat 545 by Jenny Bryan  
- [This R data import tutorial is everything you need, part 1](https://www.datacamp.com/community/tutorials/r-data-import-tutorial/#gs.DdZtwPI) from Data Camp  
- [Importing data into R, part 2](https://www.datacamp.com/community/tutorials/importing-data-r-part-two#gs.uCsWBZE) from Data Camp  







## data sites 

- [Visualizing obesity across United States by using data from Wikipedia](https://datascienceplus.com/visualizing-obesity-across-united-states-by-using-data-from-wikipedia/) 
- [Extracting tables from PDFs in R using the tabulizer package](https://datascienceplus.com/extracting-tables-from-pdfs-in-r-using-the-tabulizer-package/) 
- [Pulling data out of census spreadsheets using R](https://datascienceplus.com/pulling-data-out-of-census-spreadsheets-using-r/) 
- [Gapminder: Time series data about the world](http://www.gapminder.org/data/)
- [rOpenSci packages](https://ropensci.org/packages/#data_access)
- [Using data.gov APIs in R](http://data.library.virginia.edu/using-data-gov-apis-in-r/) 
- [Datasets for data mining and data science](http://www.kdnuggets.com/datasets/index.html)
- [US Census](https://www.census.gov/data.html) 
 

---

[main page](../README.md)<br>
[topics page](../README-by-topic.md)




