---
output: github_document
bibliography: "../manage/refs.bib" 
csl: "../manage/csl/journal-of-peace-research.csl"
---

## week 8

Portfolio progress. By the end of the week you should be able to

- Revise earlier graphs and critiques based on the roundtable discussions 
- Revise the citations used based on the assigned readings 



Due this week 

- [Written response](read-01_reading-response-form.pdf) for roundtable discussion of @DraggaVoss2001. 
- D7 Original or learn on your own graph and critique. Submitted electronically. See [portfolio requirements](folio-01_portfolio-requirements.md) and [portfolio checklist](folio-02_portfolio-checklist.pdf). 




Reading 

- @DraggaVoss2001 Cruel pies 
- @Robbins2013 Ch 8: Applying what we've learned: *Before* and *after* examples




Lecture slides

- something  
- something else 




Tutorials

- Original displays: Designing your own data graphics 
- Document design: Front and back matter 






## bibliography 

<div id="refs"></div>
  
---

[main page](../README.md)<br>
[topics page](../README-by-topic.md)
