---
output: github_document
bibliography: "../manage/refs.bib" 
csl: "../manage/csl/journal-of-peace-research.csl"
---

## week 4


New portfolio work. By the end of the week you should be able to

- Begin looking for graphical lies to redesign 
- Developing your data and table for D4 Tables 

Continuing portfolio progress

- Revise earlier graphs and critiques based on the roundtable discussions 
- Revise the citations used based on the assigned readings 

Due this week

- Present your D3 Multiway graph and critique. See [portfolio requirements](folio-01_portfolio-requirements.md) and [portfolio checklist](folio-02_portfolio-checklist.pdf). 

Reading 

- @Few2012 Differing roles of tables and graphs
- @Wainer2000 How to display data badly

Lecture slides

- [Principles and practices of table design](../slides/Le16-tables.pdf)
- something else  

Tutorials
 
- [Tables](tut-1301_tables.md) 
- [Factors](tut-1401_factors.md) 
- Compare your work to my version of the [factors tutorial script](../practiceR/tut14_factors.R)


## bibliography 

<div id="refs"></div>
  
---

[main page](../README.md)<br>
[topics page](../README-by-topic.md)
