---
output: github_document
bibliography: "../manage/refs.bib" 
csl: "../manage/csl/journal-of-peace-research.csl"
---


## week 3

Portfolio progress. By the end of the week you should be able to

- Create the D3 multiway plot and draft its critique 
- Transform data using select(), filter, group_by(), and summarize() 
- Revise earlier graphs and critiques based on the roundtable discussions 
- Revise the citations used based on the assigned readings 


Due this week

- [Written response](read-01_reading-response-form.pdf) for roundtable discussion of @Kostelnick2007. 
- D2 Dot plot and critique. Submitted electronically. See [portfolio requirements](folio-01_portfolio-requirements.md) and [portfolio checklist](folio-02_portfolio-checklist.pdf). 


Reading 

- @Kostelnick2007 The conundrum of clarity (posted to Moodle). 
- @Robbins2013 Ch 5: Trellis graphics and other ways to display more than two variable



Lecture slides

- [Managing files](../slides/Le12-file-management-basics.pdf)



Tutorials

- [Multiway data and graphs](tut-1101_multiways.md) 
- [Finding interesting data](tut-1202_data-links.md) 
- [Transforming data](tut-1201_data-transformation.md) 




## bibliography 

<div id="refs"></div>
  
---

[main page](../README.md)<br>
[topics page](../README-by-topic.md)
