---
output: github_document
bibliography: "../manage/refs.bib" 
csl: "../manage/csl/journal-of-peace-research.csl"
---


## week 2

Portfolio progress. By the end of the week you should be able to

- Use gather() and separate() for data tidying 
- Write the R script to create the D2 dot plot 
- Consider revisions to D1 based on the roundtable discussions 
- Add citations and references to the work in progress  
- Use Word Styles to begin formatting your portfolio  


Presentations

- D1 Scatterplot and critique. 
- See [portfolio requirements](folio-01_portfolio-requirements.md) for details and the [portfolio checklist](folio-02_portfolio-checklist.pdf) to check that all requirements have been met. 

Reading

- @Robbins2013 Ch 4: Some more effective graphs in one or two dimensions
- @Kostelnick1998 Conflicting standards (on Moodle)

Lecture slides 

- [Dotplots](../slides/Le07-dot-plot-slides.pdf) 
- [gather()](../slides/Le08-illustrating-gather.pdf) 


Dot plot tutorials and exercises 

- [Capture data stored in row names](tut-0701_capture-row-name-data.md)  
- [Create a dot plot](tut-0702_create-dot-plot.md)  
- [Reorder the rows of a dot plot](tut-0703_reorder-rows.md)   
- [Condition a dot plot with text](tut-0704_condition-by-text.md)  
- [Condition a dot plot with color](tut-0705_condition-by-color.md)  
- [Manually change dot plot colors](tut-0706_manual-color.md)  
- [Condition a dot plot with facets](tut-0707_condition-facets.md)  
- [Change the order of the facets](tut-0708_order-facets.md)  
- [Set the y scales free](tut-0709_free-scales.md)  
- [Rotate text in the panel strip](tut-0710_rotate-strip-text.md)  
- [Change spacing between panels](tut-0711_change-panel-spacing.md)  
- Compare your work to my version of the [tutorial script](../practiceR/tut05_dotplot-basics.R)  
- Practice what you have learned by working these [exercises](tut-0712_dotplot-exercises.md) 

Data tutorials and exercises 

- [Tidying the Virginia Deaths data](tut-0801_tidying-data-01_VADeaths.md)
- [Tidying the WHO tuberculosis data](tut-0802_tidying-data-02_who-TB.md)

Document design tutorials and exercises 

- [Citations and references basics](tut-1001_citations-references.md) 
- [Word styles basics](tut-1002_word-styles.md) 
 


## bibliography 

<div id="refs"></div>
  
---

[main page](../README.md)<br>
[topics page](../README-by-topic.md)
