---
output: github_document
bibliography: "../manage/refs.bib" 
csl: "../manage/csl/journal-of-peace-research.csl"
---

## week 5


New portfolio work. By the end of the week you should be able to

- Developing your data and graph for D5 Box and whisker plot  (or alternative graph of univariate data) 
- Using spread(), separate(), left_join(), rbind(), and cut() for data transformation
- Explain how to choose a graph type to suit the structure of a dataset  
- Apply the implications of the "15 displays about one thing" reading to the critiques in your portfolio 

Continuing portfolio progress

- Revise earlier graphs and critiques based on the roundtable discussions 
- Revise the citations used based on the assigned readings 
- Review the portfolio checklist to be sure you keep up with all the requirements 




Due this week 

- [Written response](read-01_reading-response-form.pdf) for roundtable discussion of @Wainer2014. 
- D4 Table and critique. Submitted electronically. See [portfolio requirements](folio-01_portfolio-requirements.md) and [portfolio checklist](folio-02_portfolio-checklist.pdf). 



Reading

- @Wainer2014 Fifteen displays about one thing 
- @Doumont2009 Designing the graph



Lecture slides

- something  
- something else 





Tutorials
 
- [Graphs of univariate data](tut-1501_univariate_graphs.md) 
- [Data transformation 2](tut-2201_data-transform-2.md)  


## bibliography 

<div id="refs"></div>
  
---

[main page](../README.md)<br>
[topics page](../README-by-topic.md)
