---
output: github_document
bibliography: "../manage/refs.bib" 
csl: "../manage/csl/journal-of-peace-research.csl"
---


```{r echo=FALSE}
library(knitr)
opts_knit$set(root.dir = "../")
opts_chunk$set(echo = TRUE, message = FALSE, collapse = TRUE, warning = FALSE)
```



## week 1

Portfolio progress. By the end of the week you should be able to 

- Find interesting data: tidy data only for now 
- If you download data, save it in the *data* directory 
- Write the R script to create the D1 scatterplot
- Save the R script in your *design* directory 
- Start a new Rmd file, call it *your-last-name_portfolio_v01.Rmd* 
- Save it in your *portfolio* directory 
- Use *source()* to run the R script that creates the graph 
- Write your prose critique 
- Knit the Rmd script 
- Due at the first presentation




Due this week

- [Written response](read-01_reading-response-form.pdf) for roundtable discussion of @Tufte1997. 





Reading

- @Robbins2013 Ch 2: Limitations of some common charts and graphs
- @Tufte1997 Challenger launch decision. Checkout a hard copy from me. 

Lecture slides

- [Scatterplot slides](../slides/Le03-scatterplot-slides.pdf)
- [Data basics slides](../slides/Le04-data-basics-slides.pdf) 
- [R markdown basics slides](../slides/Le06-markdown-basics-slides.pdf) 

Scatterplot tutorials and exercises

- [Start a script](tut-0301_start-scatterplot.md)
- [Install and load a package](tut-0302_install-load-package.md)
- [Create a data frame](tut-0303_create-data-frame.md)
- [Create a scatterplot](tut-0304_create-scatterplot.md)
- [Edit the data markers](tut-0305_edit-data-markers.md)
- [Edit the axis labels and title](tut-0306_edit-axis-labels-title.md)
- [Edit the scales](tut-0307_edit-scales.md)
- [Edit the theme](tut-0308_edit-theme.md)
- Compare your work to my version of the [tutorial script](../practiceR/tut02_scatterplot.R)  
- Practice what you have learned by working these [exercises](tut-0309_scatterplot-exercise.md) 

Data basics tutorials and exercises

- [Data basics](tut-0401_data-basics.md)  
- [Examine the sample Excel file](tut-0402_read-excel.md)  
- [Write and read a CSV file](tut-0403_read-write-csv.md)  
- [Examining a data set](tut-0404_examine-new-data.md)  
- [When a new library masks a function](tut-0405_new-library-masks.md)  
- [Add a regression to a scatterplot](tut-0406_add-regression.md)  
- [Accessing data in R](tut-0407_access-data-in-R.md)  
- Compare your work to my version of the [tutorial script](../practiceR/tut03_data-basics.R)  
- Practice what you have learned by working these [exercises](tut-0408_data-basics-exercise.md)  

Document design tutorials and exercises

- [Create an R markdown script](tut-0601_rmd-start-markdown.md)  
- [Edit the Rmd output format](tut-0602_rmd-edit-output.md)  
- [Basic Rmd markup tags](tut-0603_rmd-basic-tags.md)  
- [Elements of an Rmd report](tut-0604_rmd-elements.md)  
- [Run an R script from an Rmd script](tut-0605_rmd-run-r.md)  
- Compare your work to my version of the [first report](../practiceR/tut04_first-report.Rmd) or [second report](../practiceR/tut04_second-report.Rmd)
- Practice what you have learned by working these [exercises](tut-0607_rmd-exercise.md)  






## bibliography 

<div id="refs"></div>
  
---

[main page](../README.md)<br>
[topics page](../README-by-topic.md)
