---
output:
  md_document:
    variant: markdown_github
    pandoc_args: "--no-wrap"
---

#### Installing R & RStudio for Windows

I call these the "real" instructions because so many installation instructions I've encountered assume I know things that I don't know. Please let me know if these instructions fail you in any way. I'm always open to suggestions for improvement. 

_localmgr login_ 

- If you are a student or faculty member whose computer is maintained by an IT department, you will probably have a localmgr login account on your computer. If you do, you will have to login as the localmgr to install R and RStudio---it's not sufficient to have admin privileges on your usual login username. You must use localmgr. 
- If your computer is NOT maintained by an IT department, you can ignore the ``localmgr'' instructions and just login in the usual way. 

_CRAN_ 

- From the Comprehensive R Archive Network  [(CRAN)](http://cran.us.r-project.org/) download the latest version of _R for Windows_. Look for the link labeled _Install R for the very first time_. 
- Install the software in _C:/Program Files_. Accept all defaults. 






