---
output:
  md_document:
    variant: markdown_github
---

### Install R

_Mac and Linux users._  

- From the Comprehensive R Archive Network  [(CRAN)](http://cran.us.r-project.org/), select _Download R for Linux_ or _Download R for (Mac) OSX_ and follow the instructions. 

_Windows_ 

- If you are a student or faculty member whose computer is maintained by an IT department, you will probably have a localmgr login account on your computer. If you do, you will have to login as the localmgr to install R and RStudio---it's not sufficient to have admin privileges on your usual login username. You must use localmgr. 

- If your computer is NOT maintained by an IT department, you can ignore the localmgr and just login in the usual way. 

- From the Comprehensive R Archive Network  [(CRAN)](http://cran.us.r-project.org/) download the latest version of _R for Windows_. Look for the link labeled _Install R for the very first time_. 

- Install the software in _C:/Program Files_. Accept all defaults. 

### Install RStudio

RStudio is a free, open-source interface for R that includes a console, a syntax-highlighting editor, direct code execution, and tools for plotting, history, debugging, and workspace management. 

- Windows users, stay logged in as localmgr. 

- From [RStudio](http://www.rstudio.com/) > Products > RStudio > Desktop > Download RStudio Desktop > and select your platform (Windows, Mac, Linux). 

- In Windows, install the software in  _C:/Program Files_. Accept all defaults. 

- Windows users, logout/signout of localmgr. 







